#!/bin/sh
# startfast.sh sets up a new folder with files needed for AoC
#
# to get the session cookie:
# 1. go to https://adventofcode.com/2020/day/1/input while logged in
# 2. ctrl+shift+c > network > F5
# 3. under Name/File column, right click 'input' > Copy > Copy as cURL
# 4. paste it in a file called 'cookie' in the root directory of this project folder
# 5. take out everything except for the hash after "Cookie: session="
#

d=`date +%d`
c=`cat cookie`
if [[ $# -eq 0 ]] ; then
	echo "syntax: ./startfast $d"
	exit 1
fi

mkdir $1
cd $1
curl "https://adventofcode.com/2020/day/$1/input" -H "Cookie: session=$c" >> $1.input

echo "#!/usr/bin/python3" >> solve.py
echo "''' AoC $1 -- ./solve.py $1.input '''" >> solve.py
echo -e "import fileinput\n\ndef solve():" >> solve.py
echo "    ''' generated by startfast script '''" >> solve.py
echo -e "    return None\n" >> solve.py
echo -e "if __name__ == '__main__':\n    print(solve())" >> solve.py
